groups:
- name: example
  rules:
  - alert: HighCPU
    expr: avg(rate(node_cpu_seconds_total{mode="user"}[5m])) > 0.8
    for: 30s
    labels:
      severity: critical
      service: api
    annotations:
      description: CPU usage on {{ $labels.instance }} exceeds 80%
  - alert: HighLatency
    expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 0.5
    for: 1m
    labels:
      severity: warning
      service: web
    annotations:
      description: Response time > 500ms on {{ $labels.instance }} 