---
- name: Deploy Prometheus Node Exporter with Docker Compose
  hosts: nodes
  become: yes
  vars:
    app_dir: /opt/prometheus
    docker_compose_file: docker-compose.yml

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Install Docker Python module
      pip:
        name: docker
        state: present

    - name: Verify Docker Compose installation
      shell: docker compose version
      register: compose_version
      changed_when: false

    - name: Display Docker Compose version
      debug:
        var: compose_version.stdout_lines

    - name: Create prometheus directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose file
      copy:
        src: "{{ docker_compose_file }}"
        dest: "{{ app_dir }}/{{ docker_compose_file }}"
        mode: '0644'

    - name: Copy prometheus configuration
      copy:
        src: prometheus.yml
        dest: "{{ app_dir }}/prometheus.yml"
        mode: '0644'

    - name: Deploy Docker Compose stack
      shell: cd {{ app_dir }} && docker compose up -d --build
      args:
        creates: "{{ app_dir }}/.deployed" 